baseURL = "https://hanseok.github.io/bestf-blog/"
title = "Your Hugo Blog"
# theme = "book"
# theme = "m10c"
languageCode = "ko"
publishDir = "public"

[params]
  author = "꿈돌이"
  description = "일상과 관심사에 대한 끄적이"
  avatar = "images/avatar.jpg"  # static/images/avatar.jpg 위치에 파일 필요
  menu_item_separator = " - "

[params.style]
  backgroundColor = "#fff"
  textColor = "#222"
  primaryColor = "#4f6fad"

[taxonomies]
  tag = "tags"
  category = "categories"
