baseURL = 'https://blog.bestf.net/'
languageCode = "ko-kr"
title = '끄적끄적'
theme = 'm10c'

publishDir = "public"

# --- 메뉴 설정 ---
# 상단에 표시될 메뉴를 설정합니다.
[menu]
  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    identifier = "tags"
    name = "Tags"
    url = "/tags/"
    weight = 2
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 4

[params]
  author = "꿈돌이"
  description = "꿈돌이 일상과 관심사에 대한 끄적이"
  avatar = "/images/avatar.png"
  menu_item_separator = " - "

